### ISSUE TITLE
Trained model

### ISSUE THREAD

**Issue by Aswanykh** [MrinalJain17/Human-Activity-Recognition#4]
Hi,
Could you please share the trained model? As I am working with the CPU system, my training phase takes a lot of time.

**Comment by MrinalJain17** [comment]
I did not backup the trained model parameters, but I'll train the model again and update. Will try to do it ASAP.

**Comment by MrinalJain17** [comment]
The trained model is available [here](https://s3.amazonaws.com/mrinal.data/human_activity_recognition_trained_model/Model_3.weights.best.hdf5).

Will update this in the documentation soon !!

**Note that this model is trained separately, and the value of the parameters is not the same as that mentioned in the notebook**

**Comment by Aswanykh** [comment]
Thank you for the prompt reply. Could you please advice as to how to do testing on a new video using this pre-trained model?

**Comment by MrinalJain17** [comment]
1. Load the video(s) using the utility class `Videos` in `utils.py`. Read the documentation within the code [here](https://github.com/MrinalJain17/Human-Activity-Recognition/blob/master/utils.py#L15) to set the parameters.
2. Load the pre-trained model.
```python
model.load_weights('Model_3.weights.best.hdf5')
```
3. Predict on your own video.
```python
model.predict_classes(video)
```

Have a look at the notebook for further assistance.

**Comment by Aswanykh** [comment]
Hi, Thanks for your prompt reply. 
It would be helpful if you share the actual output of this model. Because what my requirement is, I need to list the activities within the video once the video is inputed.

**Comment by MrinalJain17** [comment]
Hey @Aswanykh 

I understand what you need. However, I trained my model(s) on an AWS instance and currently, I do not have any instances running (since I used up all my credits). 

I assure you that I'll link a fully trained model but this might take some time.

And, I would also suggest that you set up a GPU instance on AWS or FloydHub (the latter is much more simple and even free for a certain time period) and try to replicate the model, as I'm not sure when will I be able to do it.

But anyways, Thanks for your interest. Really appreciate it.
