### ISSUE TITLE
how to deploy this project into production 

### ISSUE THREAD

**Issue by bit-scientist** [MrinalJain17/Human-Activity-Recognition#7]
Thank you once again for this work.
I would like to try this project in real time linking it with streaming camera. 
How do you you suggest it doing?

**Comment by ghost** [comment]
@bit-scientist  +1

**Comment by MrinalJain17** [comment]
Deploying this project into production would actually be challenging. However, since this work was performed as an experiment with the intention to learn about various topics involved, I did not give much thought to this matter. 

Probably something like tensorflow.js could be used for making a web app using a model trained on videos. Or, a more complicated approach would involve creating a web server on AWS, and sending user requests via a hosted frontend. There might be numerous other ways, and elucidating on them is out of the scope of this project.
